### ISSUE TITLE
literal::Integer is unsigned

### ISSUE THREAD

**Issue by alanz** [sile/erl_ast#2]
`literal::Integer` is defined as

```rust
pub struct Integer {
    pub line: ast::LineNum,
    pub value: BigUint,
}
```

Is there a reason for using `BigUint` instead of `BigInt`?

**Comment by sile** [comment]
I'm not sure as it's too long ago I implemented `erl_ast`, but I think that it's because Erlang's AST holds all integers as non-negative forms.
[The official doc](http://erlang.org/doc/apps/erts/absform.html) says as follows:
> Notice that negative integer and float literals do not occur as such; they are parsed as an application of the unary negation operator. (8.2  Atomic Literals)
